# Generated by Django 6.0.6 on 2026-06-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarSale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('trim', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, max_length=20, null=True)),
                ('vin', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('condition', models.FloatField(blank=True, db_column='condition', null=True)),
                ('odometer', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('interior', models.CharField(blank=True, max_length=50, null=True)),
                ('seller', models.CharField(blank=True, max_length=255, null=True)),
                ('mmr', models.IntegerField(blank=True, null=True)),
                ('sellingprice', models.IntegerField(blank=True, null=True)),
                ('saledate', models.DateField(blank=True, null=True)),
                ('saleday', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Car Sale',
                'verbose_name_plural': 'Car Sales',
                'db_table': 'car_sales',
            },
        ),
    ]
